services:
  - type: web
    name: marwad-digital-menu
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.0.0
      - key: RENDER_EXTERNAL_URL
        value: https://digital-marwad-1.onrender.com
